userLoginExp/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

userLoginExp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

userLoginExp/app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :username, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 255 }, 
				format: { with: VALID_EMAIL_REGEX},
				uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	#Hash password using bcrypt
	def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
    end
end

userLoginExp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

userLoginExp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # before_filter :set_failed_login_time
  # def set_failed_login_time
  #   @login_failed = 0
  # end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      open_page_time =  params[:session][:open_page_time].to_i
      login_time = DateTime.now.to_i
      time_difference = login_time - open_page_time
      user.update_columns(:open_page_at => open_page_time, :login_at => login_time, :time_difference =>time_difference)
      redirect_to user

    # else
    #   flash.now[:danger] = 'Invalid email/password combination'
    #   render 'new'
    elsif user
      flash.now[:danger] = 'Invalid email/password combination'
      # @login_failed = @login_failed + 1
      # p @login_failed
      # current_failed_times = user.select(:login_failed)
      # p current_failed_times+1
      # user.update_columns
      render 'new'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end

  end

  def destroy
    log_out
    redirect_to root_url
  end
end

userLoginExp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

userLoginExp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	# debugger
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the User Login Experiment!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password,
                                   :password_confirmation)
    end

end

userLoginExp/app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "User Login Experiment for 2017 CSC 510"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

userLoginExp/app/helpers/sessions_helper.rb
module SessionsHelper
	#define log in method
	def log_in(user)
		session[:user_id] = user.id
	end

	#Define log out method
	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end

	#getting the current user, return current user if can be found
	def current_user
  		@current_user ||= User.find_by(id: session[:user_id])
	end

	#returns true if logged in
	def logged_in?
    	!current_user.nil?
    end



end

userLoginExp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

userLoginExp/app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

userLoginExp/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://github.com/SE17GroupH">User Login Experiment</a>
    by <a href="https://github.com/devarenacn">Yujia Harold Chen</a>
  </small>
</footer>

userLoginExp/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "User Login Experiment", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

userLoginExp/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

userLoginExp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

userLoginExp/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

userLoginExp/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | User Login Experiment for 2017 CSC 510</title>
  </head>
  <body>
    <h1>Help</h1>
	<p>
  		Get help on the website at the
  		<a href="https://github.com/SE17GroupH/userLoginExperiment">User Login Experiment GitHub page</a>.
	</p>
  </body>
</html>

userLoginExp/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | User Login Experiment for 2017 CSC 510</title>
  </head>
  <body>
    <div class="center jumbotron">
      <h1>User Login Experiment for 2017 CSC 510</h1>
      <h2>
        This is the home page for the
        <a href="https://github.com/SE17GroupH">Group H</a>
        User Login Experiment application.
      </h2>
      <h2>
        For this experiment, we need you to click on the Sign up now button and register as a new user. 
      </h2>

      <h2>
        Then click on Sign out, then log into the system again.
      </h2>

      <h2>
        And you're done. Thank you so much for your participation.
      </h2>

      <h2>
      Instructions can be found <a href="https://github.com/SE17GroupH/SE17_TeamH_Ideas/blob/master/userLoginExp/app/assets/userInstruction.pdf">here </a>
      </h2>

      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
    </div>



<%= link_to image_tag("software.png", alt: "Group H logo"),
            'https://github.com/SE17GroupH' %>
  </body>
</html>

userLoginExp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Login',

userLoginExp/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>


      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      Minimum password length is 6

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>


      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      Please try not to use remember password for this experiment.

      We will NOT see or use your password.

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

userLoginExp/app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
      <h2>
      	<%= link_to "Log out", logout_path, method: "delete" %>
      </h2>
    </section>
  </aside>
</div>